apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-user-deployment #나는 k8s-backend-user-deployment라는 이름을 가졌다
spec: #deployment입장에서 sepc이다.
  replicas: 3  # 원하는 파드 복제본 수 (기본값: 1)
  selector:
    matchLabels:
      app: k8s-backend-user  # 템플릿의 labels와 일치해야 함
  template:
    metadata:
      labels:
        app: k8s-backend-user  # selector와 일치해야 함
    spec:
      containers:
        - name: k8s-backend-user
          image: seungwon9819/k8s-backend-user:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: backend-user-config-volume
      volumes:
        - name: backend-user-config-volume
          configMap:
            name: backend-user-config #컨피그 맵의 backend-user-config 이름을 가진 파일로 접근하겠다.
            items:
              - key: application-dev.yml #key가 되는 것이 data안에 있는 이름을 의미한다.
                path: application-dev.yml #볼륨 마운트 해서 쓸 이름