apiVersion: v1
kind: Secret
metadata:
  name: backend-user-secret #이름을 backend-user-secret이다. 이 이름은 볼륨 지정해줄 때 사용
stringData:
  application-secret.yml: |
    spring:
      datasource:
        username: user
        password: 1234
